In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_json(
    "C:\\Users\\Lenovo\\Desktop\\Тест\\Занятие по pandas\\1 занятие\\pandas\\data\\auto_remix.json"
)

In [4]:
pd.options.display.float_format = '{:,.2f}'.format

In [146]:
sample = df.sample(n=200, replace=True, random_state=21)
sample

        CarNumber  Refund     Fines   Make    Model
207  96907X197RUS       1  3,000.00    BMW      NaN
48   7608EE777RUS       1  4,000.00  Skoda  Octavia
368  H907YK197RUS       2  7,100.00   Ford    Focus
120  8605T8154RUS       1  1,000.00   Ford    Focus
419  M0279X197RUS       2 36,000.00   Ford    Focus
..            ...     ...       ...    ...      ...
587  X257HE161RUS       2  5,000.00   Ford    Focus
595  X423MK197RUS       2 14,300.00   Ford    Focus
365  H889YK197RUS       2 10,600.00   Ford    Focus
474  O275O7161RUS       2 16,600.00   Ford    Focus
592  X4108H125RUS       2  1,300.00   Ford    Focus

[200 rows x 5 columns]

In [148]:
sample['Refund'] = np.random.permutation(sample['Refund'])
sample['Fines'] = np.random.permutation(sample['Fines'])
sample

        CarNumber  Refund     Fines   Make    Model
207  96907X197RUS       2  2,600.00    BMW      NaN
48   7608EE777RUS       2  3,400.00  Skoda  Octavia
368  H907YK197RUS       2  9,600.00   Ford    Focus
120  8605T8154RUS       2    400.00   Ford    Focus
419  M0279X197RUS       2  1,600.00   Ford    Focus
..            ...     ...       ...    ...      ...
587  X257HE161RUS       2    500.00   Ford    Focus
595  X423MK197RUS       1  3,100.00   Ford    Focus
365  H889YK197RUS       2  2,000.00   Ford    Focus
474  O275O7161RUS       2 19,800.00   Ford    Focus
592  X4108H125RUS       1  1,500.00   Ford    Focus

[200 rows x 5 columns]

In [150]:
car_rows = pd.concat([df, sample])
car_rows

        CarNumber  Refund     Fines  Make  Model
0    704687163RUS       2  1,400.00  Ford  Focus
1    704787163RUS       2  2,800.00  Ford  Focus
2    704987163RUS       2  8,594.59  Ford  Focus
3    705287163RUS       2  2,000.00  Ford  Focus
4    705387163RUS       2    700.00  Ford  Focus
..            ...     ...       ...   ...    ...
587  X257HE161RUS       2    500.00  Ford  Focus
595  X423MK197RUS       1  3,100.00  Ford  Focus
365  H889YK197RUS       2  2,000.00  Ford  Focus
474  O275O7161RUS       2 19,800.00  Ford  Focus
592  X4108H125RUS       1  1,500.00  Ford  Focus

[925 rows x 5 columns]

In [151]:
np.random.seed(21)

In [160]:
car_rows['Year'] = np.random.randint(low=1980, high=2021, size = len(car_rows))
car_rows

        CarNumber  Refund     Fines  Make  Model  Year
0    704687163RUS       2  1,400.00  Ford  Focus  1982
1    704787163RUS       2  2,800.00  Ford  Focus  1991
2    704987163RUS       2  8,594.59  Ford  Focus  1999
3    705287163RUS       2  2,000.00  Ford  Focus  2018
4    705387163RUS       2    700.00  Ford  Focus  1991
..            ...     ...       ...   ...    ...   ...
587  X257HE161RUS       2    500.00  Ford  Focus  1993
595  X423MK197RUS       1  3,100.00  Ford  Focus  1985
365  H889YK197RUS       2  2,000.00  Ford  Focus  2017
474  O275O7161RUS       2 19,800.00  Ford  Focus  2001
592  X4108H125RUS       1  1,500.00  Ford  Focus  1990

[925 rows x 6 columns]

In [5]:
surname = pd.read_json(
    "C:\\Users\\Lenovo\\Desktop\\Тест\\Занятие по pandas\\1 занятие\\pandas\\data\\surname.json"
)
surname

            0        1     2
0        NAME    COUNT  RANK
1       ADAMS   427865    42
2       ALLEN   482607    33
3     ALVAREZ   233983    92
4    ANDERSON   784404    15
..        ...      ...   ...
96   WILLIAMS  1625252     3
97     WILSON   801882    14
98       WOOD   250715    84
99     WRIGHT   458980    35
100     YOUNG   484447    32

[101 rows x 3 columns]

In [6]:
surname = pd.DataFrame(surname)

In [7]:
surname.columns = ['NAME', 'COUNT', 'RANK']

In [8]:
surname.drop(index = 0,inplace = True)

In [31]:
surname

         NAME    COUNT RANK
1       ADAMS   427865   42
2       ALLEN   482607   33
3     ALVAREZ   233983   92
4    ANDERSON   784404   15
5      BAILEY   277845   72
..        ...      ...  ...
96   WILLIAMS  1625252    3
97     WILSON   801882   14
98       WOOD   250715   84
99     WRIGHT   458980   35
100     YOUNG   484447   32

[100 rows x 3 columns]

In [116]:
surname.sort_values('COUNT',ascending = False)

         NAME    COUNT RANK
49      LOPEZ   874523   12
28   GONZALEZ   841025   13
97     WILSON   801882   14
4    ANDERSON   784404   15
88     THOMAS   756142   16
..        ...      ...  ...
53     MILLER  1161437    7
20      DAVIS  1116357    8
78  RODRIGUEZ  1094924    9
51   MARTINEZ  1060159   10
34  HERNANDEZ  1043281   11

[100 rows x 3 columns]

In [9]:
car_uniq = df['CarNumber'].unique()

In [10]:
car_uniq

<StringArray>
['704687163RUS', '704787163RUS', '704987163RUS', '705287163RUS',
 '705387163RUS', '705787163RUS', '7064C8197RUS', '7065C8197RUS',
 '7066C8197RUS', '707987163RUS',
 ...
 'Y960EE197RUS', 'Y963O8197RUS', 'Y964EE197RUS', 'Y964O8197RUS',
 'Y965EE197RUS', 'Y965O8197RUS', 'Y966O8197RUS', 'Y967O8197RUS',
 'Y969O8197RUS', 'Y973O8197RUS']
Length: 531, dtype: str

In [15]:
new_df = pd.DataFrame(data=car_uniq,columns=['CarNumber'])
new_df

        CarNumber
0    704687163RUS
1    704787163RUS
2    704987163RUS
3    705287163RUS
4    705387163RUS
..            ...
526  Y965O8197RUS
527  Y966O8197RUS
528  Y967O8197RUS
529  Y969O8197RUS
530  Y973O8197RUS

[531 rows x 1 columns]

In [54]:
np.random.seed(21)
new_df['id_user'] = np.random.randint(low=1, high=101, size = len(new_df))
new_df

        CarNumber  id_user
0    704687163RUS       74
1    704787163RUS       80
2    704987163RUS       57
3    705287163RUS        5
4    705387163RUS       49
..            ...      ...
526  Y965O8197RUS       10
527  Y966O8197RUS       32
528  Y967O8197RUS        6
529  Y969O8197RUS       21
530  Y973O8197RUS       57

[531 rows x 2 columns]

In [55]:
df_id_users = pd.merge(df,new_df,on = 'CarNumber',how = 'inner')
df_id_users

        CarNumber  Refund     Fines  Make  Model  id_user
0    704687163RUS       2  1,400.00  Ford  Focus       74
1    704787163RUS       2  2,800.00  Ford  Focus       80
2    704987163RUS       2  8,594.59  Ford  Focus       57
3    705287163RUS       2  2,000.00  Ford  Focus        5
4    705387163RUS       2    700.00  Ford  Focus       49
..            ...     ...       ...   ...    ...      ...
720  Y969O8197RUS       2  7,800.00  Ford  Focus       21
721  Y969O8197RUS       1 15,600.00  Ford  Focus       21
722  Y973O8197RUS       1 34,800.00  Ford  Focus       57
723  Y973O8197RUS       1 69,600.00  Ford  Focus       57
724  Y973O8197RUS       2  8,594.59  Ford  Focus       57

[725 rows x 6 columns]

In [56]:
id_users = surname.reset_index().rename(columns = {'index':'id_user'})
id_users

    id_user      NAME    COUNT RANK
0         1     ADAMS   427865   42
1         2     ALLEN   482607   33
2         3   ALVAREZ   233983   92
3         4  ANDERSON   784404   15
4         5    BAILEY   277845   72
..      ...       ...      ...  ...
95       96  WILLIAMS  1625252    3
96       97    WILSON   801882   14
97       98      WOOD   250715   84
98       99    WRIGHT   458980   35
99      100     YOUNG   484447   32

[100 rows x 4 columns]

In [57]:
result = pd.merge(df_id_users,id_users,on = 'id_user', how = 'inner')
auto_user = result[['CarNumber','NAME']]
auto_user

        CarNumber        NAME
0    704687163RUS  RICHARDSON
1    704787163RUS        ROSS
2    704987163RUS      MORGAN
3    705287163RUS      BAILEY
4    705387163RUS       LOPEZ
..            ...         ...
720  Y969O8197RUS        DIAZ
721  Y969O8197RUS        DIAZ
722  Y973O8197RUS      MORGAN
723  Y973O8197RUS      MORGAN
724  Y973O8197RUS      MORGAN

[725 rows x 2 columns]

In [135]:
name = surname['NAME']

In [ ]:
name = df.sample(n = len(car_uniq),replace = True, random_state=21)

In [139]:
new_df = pd.DataFrame(columns = ['CarNumber','SURNAME'])

In [ ]:
sample = df.sample(n=200, replace=True, random_state=21)

        CarNumber  Refund     Fines   Make    Model
207  96907X197RUS       2 21,800.00    BMW      NaN
48   7608EE777RUS       2  7,000.00  Skoda  Octavia
368  H907YK197RUS       2  3,000.00   Ford    Focus
120  8605T8154RUS       2  1,300.00   Ford    Focus
419  M0279X197RUS       1  1,000.00   Ford    Focus
..            ...     ...       ...    ...      ...
587  X257HE161RUS       2  3,100.00   Ford    Focus
595  X423MK197RUS       1    100.00   Ford    Focus
365  H889YK197RUS       1    100.00   Ford    Focus
474  O275O7161RUS       2  1,100.00   Ford    Focus
592  X4108H125RUS       1 20,600.00   Ford    Focus

[200 rows x 5 columns]

In [ ]:
#Добавим к нового дата фрейме 5 рандомных уникальных,значений для двух столбцов
name_uniq = name.unique()
new_df['CarNumber']=car_uniq.sample(n = 5)

AttributeError: 'StringArray' object has no attribute 'sample'

In [ ]:
new_df.sample(n = 5,)

Empty DataFrame
Columns: [CarNumber, SURNAME]
Index: []