In [94]:
import pandas as pd
import numpy as np

In [103]:
df = pd.read_csv(
"C:\\Users\\Lenovo\\Desktop\\Тест\\Занятие по pandas\\1 занятие\\pandas\\data\\fines.csv"
)
df

        CarNumber  Refund        Fines   Make    Model  Year
0    704687163RUS       2  1400.000000   Ford    Focus  1989
1    704787163RUS       2  2800.000000   Ford    Focus  1995
2    704987163RUS       2  8594.586466   Ford    Focus  1984
3    705287163RUS       2  2000.000000   Ford    Focus  2015
4    705387163RUS       2   700.000000   Ford    Focus  2014
..            ...     ...          ...    ...      ...   ...
920  708487163RUS       1  1000.000000   Ford    Focus  1996
921   X795O796RUS       1  1000.000000   Ford    Focus  1981
922  O77997197RUS       2  5600.000000   Ford    Focus  1983
923  T478KX197RUS       2  7500.000000   Ford    Focus  2004
924  T242H8197RUS       2  8594.586466  Skoda  Octavia  1984

[925 rows x 6 columns]

In [80]:
%%timeit
data = []
for i in range(0,len(df)):
    data.append(df.iloc[i]['Fines'] / df.iloc[i]['Refund'] * df.iloc[i]['Year'])
'''
oop: write a function that iterates through the dataframe using for i in range(0, len(df)), iloc and append() to a list, assign the result of the func- tion to a new column in the dataframe
'''

352 ms ± 21.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [82]:
%%timeit
data_2 = []
for i  in df.iterrows():
    data_2.append(i[1]['Fines'] / i[1]['Refund'] * i[1]['Year'])
#do it using iterrows()

74 ms ± 5.05 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [83]:
%%timeit
data_3 = []
df.apply(
    lambda new : data_3.append(
    new['Fines']/new['Refund'] * new['Year']),
    axis = 1)
#do it using apply() and lambda function

21.5 ms ± 2.09 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [84]:
%%timeit
df['New'] = df['Fines'] / df['Refund'] * df['Year']
#do it using Series objects from the dataframe

343 μs ± 8.33 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [85]:
%%timeit
df['New'] = df['Fines'].values / df['Refund'].values * df['Year'].values
#do it as in the previous subtask but with the method .values

213 μs ± 30.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [86]:
%%timeit
df[df['CarNumber'] == 'O136HO197RUS']
#get a row for a specific CarNumber, for example, ’O136HO197RUS’

788 μs ± 22.2 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [ ]:
df.set_index('CarNumber', inplace=True)
df

In [107]:
df.info(memory_usage='deep'),

<class 'pandas.DataFrame'>
Index: 925 entries, 704687163RUS to T242H8197RUS
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Refund  925 non-null    int64
 1   Fines   925 non-null    float64
 2   Make    925 non-null    str
 3   Model   912 non-null    str
 4   Year    925 non-null    int64
dtypes: float64(1), int64(2), str(2)
memory usage: 63.0 KB

(None,)

In [109]:
df_copy = df.copy(deep = True)
df_copy

              Refund        Fines   Make    Model  Year
CarNumber
704687163RUS       2  1400.000000   Ford    Focus  1989
704787163RUS       2  2800.000000   Ford    Focus  1995
704987163RUS       2  8594.586466   Ford    Focus  1984
705287163RUS       2  2000.000000   Ford    Focus  2015
705387163RUS       2   700.000000   Ford    Focus  2014
...              ...          ...    ...      ...   ...
708487163RUS       1  1000.000000   Ford    Focus  1996
X795O796RUS        1  1000.000000   Ford    Focus  1981
O77997197RUS       2  5600.000000   Ford    Focus  1983
T478KX197RUS       2  7500.000000   Ford    Focus  2004
T242H8197RUS       2  8594.586466  Skoda  Octavia  1984

[925 rows x 5 columns]