In [156]:
import pandas as pd
import numpy as np

In [157]:
df = pd.read_json(
    "C:\\Users\\Lenovo\\Desktop\\Тест\\Занятие по pandas\\1 занятие\\pandas\\data\\auto_remix.json"
)

In [158]:
pd.options.display.float_format = '{:,.2f}'.format

In [222]:
sample = df.sample(n=200, replace = False, random_state=21)
sample

        CarNumber  Refund     Fines   Make    Model
445  M580CH197RUS       2 47,500.00   Ford    Focus
22    7183TT36RUS       2  5,400.00   Ford    Focus
93   8311XX154RUS       2  4,300.00   Ford    Focus
173  9468EX178RUS       1  4,000.00   Ford    Focus
697  Y7689C197RUS       2 45,000.00   Ford    Focus
..            ...     ...       ...    ...      ...
14   708487163RUS       1  1,000.00   Ford    Focus
623   X795O796RUS       1  1,000.00   Ford    Focus
498  O77997197RUS       2  5,600.00   Ford    Focus
536  T478KX197RUS       2  7,500.00   Ford    Focus
520  T242H8197RUS       2  8,594.59  Skoda  Octavia

[200 rows x 5 columns]

In [227]:
'''
enrich the dataframe concat_rows by a new column with the data generated

create a series with the name Year using random integers from 1980 to 2019
'''
np.random.seed(21)
car_rows['Year'] = np.random.randint(low=1980, high=2021, size = len(car_rows))
fines = car_rows
fines

        CarNumber  Refund    Fines   Make    Model  Year
0    704687163RUS       2 1,400.00   Ford    Focus  1989
1    704787163RUS       2 2,800.00   Ford    Focus  1995
2    704987163RUS       2 8,594.59   Ford    Focus  1984
3    705287163RUS       2 2,000.00   Ford    Focus  2015
4    705387163RUS       2   700.00   Ford    Focus  2014
..            ...     ...      ...    ...      ...   ...
14   708487163RUS       1 1,000.00   Ford    Focus  1996
623   X795O796RUS       1 1,000.00   Ford    Focus  1981
498  O77997197RUS       2 5,600.00   Ford    Focus  1983
536  T478KX197RUS       2 7,500.00   Ford    Focus  2004
520  T242H8197RUS       2 8,594.59  Skoda  Octavia  1984

[925 rows x 6 columns]

In [228]:
'''
create a new dataframe with the car numbers and their owners
* get the most popular surnames(**you can find the file surname.json in the attachments**) in the US
'''
surname = pd.read_json(
    "C:\\Users\\Lenovo\\Desktop\\Тест\\Занятие по pandas\\1 занятие\\pandas\\data\\surname.json"
)
surname

            0        1     2
0        NAME    COUNT  RANK
1       ADAMS   427865    42
2       ALLEN   482607    33
3     ALVAREZ   233983    92
4    ANDERSON   784404    15
..        ...      ...   ...
96   WILLIAMS  1625252     3
97     WILSON   801882    14
98       WOOD   250715    84
99     WRIGHT   458980    35
100     YOUNG   484447    32

[101 rows x 3 columns]

In [229]:
surname = pd.DataFrame(surname)

In [231]:
surname.columns = ['NAME', 'COUNT', 'RANK']

In [232]:
surname.drop(index = 0,inplace = True)
surname

         NAME    COUNT RANK
1       ADAMS   427865   42
2       ALLEN   482607   33
3     ALVAREZ   233983   92
4    ANDERSON   784404   15
5      BAILEY   277845   72
..        ...      ...  ...
96   WILLIAMS  1625252    3
97     WILSON   801882   14
98       WOOD   250715   84
99     WRIGHT   458980   35
100     YOUNG   484447   32

[100 rows x 3 columns]

In [233]:
#get the most popular surnames(**you can find the file surname.json in the attachments**) in the US
surname.sort_values('COUNT',ascending = False)

         NAME    COUNT RANK
49      LOPEZ   874523   12
28   GONZALEZ   841025   13
97     WILSON   801882   14
4    ANDERSON   784404   15
88     THOMAS   756142   16
..        ...      ...  ...
53     MILLER  1161437    7
20      DAVIS  1116357    8
78  RODRIGUEZ  1094924    9
51   MARTINEZ  1060159   10
34  HERNANDEZ  1043281   11

[100 rows x 3 columns]

In [170]:
'''create a new series with the surnames (they should not have
      special char-
      acters like commas, brackets, etc.) from the data you gathered, the count
      should be equal to the number of unique car numbers using the sample
      (use random_state = 21)
'''
car_uniq = df['CarNumber'].unique()
car_uniq

<StringArray>
['704687163RUS', '704787163RUS', '704987163RUS', '705287163RUS',
 '705387163RUS', '705787163RUS', '7064C8197RUS', '7065C8197RUS',
 '7066C8197RUS', '707987163RUS',
 ...
 'Y960EE197RUS', 'Y963O8197RUS', 'Y964EE197RUS', 'Y964O8197RUS',
 'Y965EE197RUS', 'Y965O8197RUS', 'Y966O8197RUS', 'Y967O8197RUS',
 'Y969O8197RUS', 'Y973O8197RUS']
Length: 531, dtype: str

In [171]:
#Уникальные автомобили
uniq_car = pd.DataFrame(data=car_uniq,columns=['CarNumber'])
uniq_car

        CarNumber
0    704687163RUS
1    704787163RUS
2    704987163RUS
3    705287163RUS
4    705387163RUS
..            ...
526  Y965O8197RUS
527  Y966O8197RUS
528  Y967O8197RUS
529  Y969O8197RUS
530  Y973O8197RUS

[531 rows x 1 columns]

In [172]:
#Создаем юзер айди для всех уникальных автомобилей
np.random.seed(21)
uniq_car['id_user'] = np.random.randint(low=1, high=101, size = len(new_df))
uniq_car

        CarNumber  id_user
0    704687163RUS       74
1    704787163RUS       80
2    704987163RUS       57
3    705287163RUS        5
4    705387163RUS       49
..            ...      ...
526  Y965O8197RUS       10
527  Y966O8197RUS       32
528  Y967O8197RUS        6
529  Y969O8197RUS       21
530  Y973O8197RUS       57

[531 rows x 2 columns]

In [173]:
#Поднимаем индекс в столбец и перемеиновыем его в id_user
id_users = surname.reset_index().rename(columns = {'index':'id_user'})
id_users

    id_user      NAME    COUNT RANK
0         1     ADAMS   427865   42
1         2     ALLEN   482607   33
2         3   ALVAREZ   233983   92
3         4  ANDERSON   784404   15
4         5    BAILEY   277845   72
..      ...       ...      ...  ...
95       96  WILLIAMS  1625252    3
96       97    WILSON   801882   14
97       98      WOOD   250715   84
98       99    WRIGHT   458980   35
99      100     YOUNG   484447   32

[100 rows x 4 columns]

In [174]:
сar_users = pd.merge(uniq_car,id_users,on = 'id_user',how = 'inner')
сar_users

        CarNumber  id_user        NAME   COUNT RANK
0    704687163RUS       74  RICHARDSON  259798   80
1    704787163RUS       80        ROSS  229368   98
2    704987163RUS       57      MORGAN  286280   69
3    705287163RUS        5      BAILEY  277845   72
4    705387163RUS       49       LOPEZ  874523   12
..            ...      ...         ...     ...  ...
526  Y965O8197RUS       10    CAMPBELL  386157   47
527  Y966O8197RUS       32        HALL  407076   45
528  Y967O8197RUS        6       BAKER  419586   44
529  Y969O8197RUS       21        DIAZ  347636   55
530  Y973O8197RUS       57      MORGAN  286280   69

[531 rows x 5 columns]

In [195]:
#create the dataframe owners with 2 columns: CarNumber and SURNAME 
owner = сar_users[['CarNumber','NAME']]
owner

        CarNumber        NAME
0    704687163RUS  RICHARDSON
1    704787163RUS        ROSS
2    704987163RUS      MORGAN
3    705287163RUS      BAILEY
4    705387163RUS       LOPEZ
..            ...         ...
526  Y965O8197RUS    CAMPBELL
527  Y966O8197RUS        HALL
528  Y967O8197RUS       BAKER
529  Y969O8197RUS        DIAZ
530  Y973O8197RUS      MORGAN

[531 rows x 2 columns]

In [234]:
'''
append 5 more observations to the fines dataframe (come up with your own
ideas of CarNumber, etc.)
'''
#Найдем минимальные и максимальные штрафы
low_fines = df['Fines'].min()
high_fines = df['Fines'].max()

In [236]:
#Возьму рандомные 5 значения с исходного датафрейма и создам рандомные значения
num_symbols = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'

data_fines = pd.DataFrame(
    {'CarNumber':[''.join(np.random.choice(list(num_symbols),size = 5)) + 
    ''.join(map(str,np.random.randint(0,10,size = 3))) + "RUS" for i in range(5)],
    'Refund':np.random.choice([1,2],size = 5),
    'Fines':np.random.randint(low_fines,high_fines,size = 5),
    'Make':['Mercedes-Benz','Hyundai','Kia','Renault','Nissan'],
    'Model':['GLC','Sonata','Sportage','Logan','Qashqai'],
    'Year': np.random.randint(1990,2026,size = 5)
}
)
data_fines

     CarNumber  Refund   Fines           Make     Model  Year
0  RUD4O497RUS       2   59195  Mercedes-Benz       GLC  2006
1  VXKHK115RUS       1  125406        Hyundai    Sonata  2024
2  2NDXU638RUS       1  111207            Kia  Sportage  2009
3  GM67G969RUS       2  176163        Renault     Logan  1997
4  JOJA5468RUS       2  133220         Nissan   Qashqai  2000

In [237]:
'''
delete the dataframe last 20 observations from the owners and add 3 new
observations (they are not the same as those you add to the fines dataframe)
'''
owner = owner.iloc[:-20]
owner

        CarNumber        NAME
0    704687163RUS  RICHARDSON
1    704787163RUS        ROSS
2    704987163RUS      MORGAN
3    705287163RUS      BAILEY
4    705387163RUS       LOPEZ
..            ...         ...
489  Y357O8197RUS     ROBERTS
490  Y358O8197RUS        LONG
491  Y359EY197RUS       LEWIS
492  Y359O8197RUS       MYERS
493   Y388E877RUS      THOMAS

[494 rows x 2 columns]

In [238]:
#add 3 new observations (they are not the same as those you add to the fines dataframe)
num_symbols = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'

new_surname = pd.DataFrame(
    {'CarNumber':[''.join(np.random.choice(list(num_symbols),size = 3)) + 
    ''.join(map(str,np.random.randint(0,10,size = 3))) + "RUS" for i in range(3)],
    'NAME':['Oleg','Kirill','Nikolay']
}
)
new_surname

   CarNumber     NAME
0  HQL733RUS     Oleg
1  FSG454RUS   Kirill
2  0PG996RUS  Nikolay

In [239]:
owner = pd.concat([owner,new_surname], ignore_index=True)
owner

        CarNumber        NAME
0    704687163RUS  RICHARDSON
1    704787163RUS        ROSS
2    704987163RUS      MORGAN
3    705287163RUS      BAILEY
4    705387163RUS       LOPEZ
..            ...         ...
492  Y359O8197RUS       MYERS
493   Y388E877RUS      THOMAS
494     HQL733RUS        Oleg
495     FSG454RUS      Kirill
496     0PG996RUS     Nikolay

[497 rows x 2 columns]

In [240]:
'''
join both dataframes: the new dataframe should have only the car numbers that exist in both dataframes
'''
all_data = pd.merge(fines,owner,on = 'CarNumber', how = 'inner')
all_data

        CarNumber  Refund    Fines   Make    Model  Year        NAME
0    704687163RUS       2 1,400.00   Ford    Focus  1989  RICHARDSON
1    704787163RUS       2 2,800.00   Ford    Focus  1995        ROSS
2    704987163RUS       2 8,594.59   Ford    Focus  1984      MORGAN
3    705287163RUS       2 2,000.00   Ford    Focus  2015      BAILEY
4    705387163RUS       2   700.00   Ford    Focus  2014       LOPEZ
..            ...     ...      ...    ...      ...   ...         ...
847  708487163RUS       1 1,000.00   Ford    Focus  1996        KING
848   X795O796RUS       1 1,000.00   Ford    Focus  1981      HUGHES
849  O77997197RUS       2 5,600.00   Ford    Focus  1983        WARD
850  T478KX197RUS       2 7,500.00   Ford    Focus  2004        LONG
851  T242H8197RUS       2 8,594.59  Skoda  Octavia  1984    ROBINSON

[852 rows x 7 columns]

In [241]:
data_fines = pd.merge(fines,owner,on = 'CarNumber', how = 'left')
data_fines

        CarNumber  Refund    Fines   Make    Model  Year        NAME
0    704687163RUS       2 1,400.00   Ford    Focus  1989  RICHARDSON
1    704787163RUS       2 2,800.00   Ford    Focus  1995        ROSS
2    704987163RUS       2 8,594.59   Ford    Focus  1984      MORGAN
3    705287163RUS       2 2,000.00   Ford    Focus  2015      BAILEY
4    705387163RUS       2   700.00   Ford    Focus  2014       LOPEZ
..            ...     ...      ...    ...      ...   ...         ...
920  708487163RUS       1 1,000.00   Ford    Focus  1996        KING
921   X795O796RUS       1 1,000.00   Ford    Focus  1981      HUGHES
922  O77997197RUS       2 5,600.00   Ford    Focus  1983        WARD
923  T478KX197RUS       2 7,500.00   Ford    Focus  2004        LONG
924  T242H8197RUS       2 8,594.59  Skoda  Octavia  1984    ROBINSON

[925 rows x 7 columns]

In [242]:
data_owner = pd.merge(owner,fines,on = 'CarNumber', how = 'left')
data_owner

        CarNumber        NAME  Refund     Fines  Make  Model     Year
0    704687163RUS  RICHARDSON    2.00  1,400.00  Ford  Focus 1,989.00
1    704787163RUS        ROSS    2.00  2,800.00  Ford  Focus 1,995.00
2    704987163RUS      MORGAN    2.00  8,594.59  Ford  Focus 1,984.00
3    705287163RUS      BAILEY    2.00  2,000.00  Ford  Focus 2,015.00
4    705387163RUS       LOPEZ    2.00    700.00  Ford  Focus 2,014.00
..            ...         ...     ...       ...   ...    ...      ...
850   Y388E877RUS      THOMAS    2.00  9,500.00  Ford  Focus 1,999.00
851   Y388E877RUS      THOMAS    2.00 19,000.00  Ford  Focus 2,004.00
852     HQL733RUS        Oleg     NaN       NaN   NaN    NaN      NaN
853     FSG454RUS      Kirill     NaN       NaN   NaN    NaN      NaN
854     0PG996RUS     Nikolay     NaN       NaN   NaN    NaN      NaN

[855 rows x 7 columns]

In [243]:
'''create a pivot table from the fines dataframe, it should look like this (the values are the sums of the fines),
 but with all the years (the values may be different for you):
'''
pivot_table = fines.pivot_table(values = 'Fines',index = 'Year',columns = 'Make',aggfunc='sum',)
pivot_table

Make     Audi      BMW       Ford      Skoda    Toyota  Volkswagen     Volvo
Year
1980      NaN      NaN  93,500.00   4,000.00 19,600.00    6,100.00       NaN
1981      NaN      NaN  86,383.76   8,200.00       NaN   18,700.00       NaN
1982      NaN      NaN 179,589.17   4,000.00  9,094.59   19,394.59       NaN
1983      NaN      NaN 107,483.76  18,900.00       NaN         NaN       NaN
1984      NaN      NaN  49,283.76  12,094.59       NaN    8,594.59       NaN
1985      NaN      NaN 359,483.76   6,000.00       NaN      300.00       NaN
1986      NaN      NaN  94,000.00   7,500.00  8,400.00         NaN       NaN
1987      NaN      NaN 179,289.17        NaN       NaN    8,100.00       NaN
1988      NaN      NaN 121,494.59        NaN  1,800.00   25,200.00       NaN
1989      NaN      NaN 112,200.00  39,800.00       NaN   20,800.00       NaN
1990      NaN      NaN  90,389.17   8,594.59  8,600.00   55,000.00       NaN
1991      NaN      NaN 166,689.17  63,300.00 21,294.59      500.00       NaN
1992      NaN      NaN 141,372.93  25,689.17       NaN   15,894.59       NaN
1993      NaN 6,500.00 227,694.59   9,594.59  6,800.00    9,500.00       NaN
1994      NaN      NaN 232,600.00   3,100.00       NaN   10,400.00       NaN
1995      NaN      NaN 181,894.59        NaN       NaN   29,700.00       NaN
1996      NaN      NaN 135,194.59   2,000.00    900.00   24,000.00       NaN
1997      NaN      NaN  79,400.00   1,000.00       NaN    1,300.00       NaN
1998      NaN      NaN 113,994.59     300.00  3,200.00    8,100.00  6,800.00
1999      NaN      NaN 124,589.17   1,900.00 35,800.00    4,600.00       NaN
2000      NaN      NaN 172,694.59        NaN 38,900.00   26,594.59 10,200.00
2001      NaN      NaN  50,900.00        NaN  4,400.00    9,600.00       NaN
2002 4,200.00      NaN  99,189.17  13,300.00 41,800.00   30,900.00       NaN
2003      NaN      NaN  90,789.17   8,500.00 34,400.00    1,300.00       NaN
2004      NaN      NaN 215,900.00        NaN  6,500.00    6,300.00       NaN
2005      NaN 3,000.00 168,972.93  16,300.00 13,000.00         NaN       NaN
2006      NaN 8,594.59  44,200.00   5,100.00 13,000.00   12,100.00       NaN
2007 4,200.00 6,500.00  86,794.59   9,094.59       NaN    1,600.00       NaN
2008      NaN      NaN 161,689.17   1,000.00       NaN         NaN       NaN
2009      NaN      NaN 319,794.59  10,200.00 11,000.00   18,594.59       NaN
2010      NaN      NaN 104,583.76     700.00  8,594.59   13,400.00       NaN
2011      NaN      NaN 158,200.00  12,700.00       NaN  168,000.00       NaN
2012      NaN      NaN 149,000.00   2,600.00 18,500.00      900.00       NaN
2013      NaN      NaN 185,489.17   8,594.59 31,100.00   41,900.00       NaN
2014      NaN      NaN 133,789.17 153,594.59  8,594.59   14,000.00       NaN
2015      NaN      NaN 211,589.17  85,894.59       NaN    3,800.00       NaN
2016      NaN      NaN 168,189.17   6,000.00       NaN   50,000.00       NaN
2017      NaN      NaN  91,794.59  10,894.59 22,400.00    1,400.00       NaN
2018      NaN      NaN 180,994.59        NaN       NaN   30,400.00       NaN
2019      NaN      NaN 176,494.59        NaN  6,400.00      300.00       NaN
2020      NaN      NaN 182,700.00   3,500.00 30,300.00         NaN       NaN

In [244]:
'''
save both the fines and owners dataframes to CSV files without an index
'''
fines.to_csv(
    'C:\\Users\\Lenovo\\Desktop\\Тест\\Занятие по pandas\\1 занятие\\pandas\\data\\fines.csv',
    index = False)
owner.to_csv(
    'C:\\Users\\Lenovo\\Desktop\\Тест\\Занятие по pandas\\1 занятие\\pandas\\data\\owner.csv',
    index = False)